language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - npm install
  - bower install
  - grunt

php:
  - 5.4
  - 5.5
  - 5.6

script: bin/phpunit --configuration phpunit.xml --coverage-text
