language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - npm install bower less grunt-cli -g
  - npm install
  - bower install
  - grunt

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

script: phpunit --configuration phpunit.xml --coverage-text
