# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php-version = "8.3.0"

[source]
paths = ["./phpmyfaq/src/phpMyFAQ"]
includes = ["./phpmyfaq/src/libs"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
inline-empty-constructor-braces = false
null-type-hint = "question"

[linter]
integrations = ["symfony", "php-unit"]

[linter.rules]
cyclomatic-complexity = { threshold = 50 }
halstead = { volume-threshold = 3000, effort-threshold = 20000 }
kan-defect = { threshold = 3.0 }
too-many-enum-cases = { threshold = 50 }
too-many-methods = { threshold = 20 }
too-many-properties = { threshold = 15 }
