site_name: phpMyFAQ v4.2
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
nav:
  - 1. Introduction: 'index.md'
  - 2. Installation: 'installation.md'
  - 3. Production Deployment: 'deployment.md'
  - 4. Docker Cheat Sheet: 'docker-cheatsheet.md'
  - 5. Updating phpMyFAQ: 'update.md'
  - 6. Use phpMyFAQ: 'usage.md'
  - 7. Manage phpMyFAQ: 'administration.md'
  - 8. AI-Assisted Translation Feature: 'ai-translation.md'
  - 9. Developer documentation: 'development.md'
  - 10. Plugins: 'plugins.md'
  - 11. MCP Server: 'mcp-server.md'
  - 12. Thank you!: 'thank-you.md'
